### ISSUE TITLE
SyntaxError:invalid syntax(calibre_plugins.dedrm__init__, line 168)

### ISSUE THREAD

**Issue by Fukumasuta** [apprenticeharper/DeDRM_tools#1179]
Hello there,

First time trying to install this plugin and i have this error when trying to import it :

`SyntaxError:invalid syntax(calibre_plugins.dedrm__init__, line 168)`

I have Calibre v. 4.19 and tried with plugin -v 6.8, 6.7 and 6.6.3 but the same error message appeared. 

Is there a way to fix this?

**Comment by ElleKayEm** [comment]
Is your calibre part of a Linux package?  Try the official release which has Python 2.  DeDRM isn't compatible with Python 3 yet.

**Comment by spartanhooah** [comment]
I have Calibre 4.21 and got this error:
`calibre, version 4.21.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'C:\\Users\\spart\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file

calibre 4.21 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 2.7.16+
Windows: ('10', '10.0.19041', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: EpubCheck (0, 2, 3) && EpubMerge (2, 9, 0) && EpubSplit (2, 9, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 194, in load
  File "site-packages\calibre\customize\zipplugin.py", line 292, in _locate_code
InvalidPlugin: The plugin in u'C:\\Users\\spart\\Downloads\\DeDRM_tools_6.8.0.zip' is invalid. It does not contain a top-level __init__.py file
`

Is this error due to the same root cause? If so, where can I find a distribution of Calibre which is bundled with Python 2 instead of 3?

**Comment by ElleKayEm** [comment]
@spartanhooah 
Your issue is caused by trying to load the whole archive.  Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.

**Comment by spartanhooah** [comment]
> 
> 
> @spartanhooah
> Your issue is caused by trying to load the whole archive. Unzip DeDRM_tools_6.8.0.zip and load DeDRM_Plugin.zip.

Ahhh, sure enough. Thanks!

**Comment by Fukumasuta** [comment]
Sorry for being late. 
Thanks for the reply but i just cannot find the official release.
I got Calibre from Portage (GNU/Gentoo).

**Comment by ElleKayEm** [comment]
https://calibre-ebook.com/

**Comment by cristoBasstard** [comment]
it gave me this problem,
SyntaxError:invalid syntax (calibre_plugins.dedrm. init 
line 168) 
I solved it just by entering the amazon account and unregistering the kindle 1.17, then I register on the kindle and that's it

**Comment by tartley** [comment]
I think this issue can be closed

**Comment by ElleKayEm** [comment]
> it gave me this problem,
> SyntaxError:invalid syntax (calibre_plugins.dedrm. init
> line 168)
> I solved it just by entering the amazon account and unregistering the kindle 1.17, then I register on the kindle and that's it

That's a solution to a different issue.
