### ISSUE TITLE
new release won't work?

### ISSUE THREAD

**Issue by nachtenhexe** [apprenticeharper/DeDRM_tools#128]
I try to install new release on Calibre and get an error message "Invalid plugin".  Am I doing something wrong?

**Comment by ElleKayEm** [comment]
Unzip the file and look in the DeDRM calibre plugin folder for the zip that you load into calibre.

**Comment by nachtenhexe** [comment]
Thank you.  A previous plugin had installed directly from the zip file.  However, now that it's installed, it doesn't seem to be doing what it's designed to do.  I attempt to load my purchased books from kobo in calibre, and still get an error message.  Am I missing a step?
 Mother is the name for God in the lips and hearts of little children.--William Makepeace Thakeray

**Comment by ElleKayEm** [comment]
Are you downloading your Kobo books with Adobe Digital Editions?  If you're using the Kobo Desktop program, then you need to install the Obok plugin (also included in the download here).

**Comment by nachtenhexe** [comment]
I installed obok, but get an error message with that, also.  it says "database error: file is encrypted or not a database".
 Mother is the name for God in the lips and hearts of little children.--William Makepeace Thakeray

**Comment by ElleKayEm** [comment]
If you're definitely using the Desktop program and not the Windows 8/10 app, it may have updated and broken the Obok plugin.  If you have a Kobo device, you could try importing books from it.

Otherwise, you can download regular epubs from the Kobo website.  Those with DRM can be downloaded with Adobe Digital Editions and decrypted with the DeDRM plugin.  Use ADE version 2.0.1 and authorize it with an Adobe ID.

**Comment by apprenticeharper** [comment]
The obok plugin should be updated in an official release soon. Until then you can try the version in the repository. See the specific issue for the link.
