### ISSUE TITLE
Calibre 4.23 DeDrm 6.8 on Catalina Not working

### ISSUE THREAD

**Issue by ptbriody** [apprenticeharper/DeDRM_tools#1312]
Getting an error trying to convert via USB download Kindle eInk with Calibre 4.23 and DeDrm 6.8 on Catalina. Worked fine before I upgraded Calibre; I've reverted back to the versions I believe should work, but getting an error on DeDrm. Below is the debug log. Thanks for any help!

calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
calibre 4.23  embedded-python: True is64bit: True
Darwin-19.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 34, 0) && DeDRM (6, 8, 0) && Package KFX (from KFX Input) (1, 34, 0) && KFX metadata reader (from KFX Input) (1, 34, 0) && KFX Input (1, 34, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000163 x 108.50000163
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.26] splash screen shown
[0.26] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[0.98] main UI initialized...
[0.98] Hiding splash screen
[3.73] splash screen hidden
[3.73] Started up in 3.73 seconds with 297 books
Worker Launch took: 0.108466148376
Job: 0 Convert book 1 of 1 (Dreams of Light) finished
Convert book 1 of 1 (Dreams of Light)
	Conversion options changed from defaults:
	  verbose: 2
	  read_metadata_from_opf: u'/var/folders/2y/6v0z6hpx4dld3z66yqzqglnh0000gn/C/calibre_4.23.0_tmp_iujYOS/OjYbwN.opf'
	  cover: u'/var/folders/2y/6v0z6hpx4dld3z66yqzqglnh0000gn/C/calibre_4.23.0_tmp_iujYOS/6_ST3g.jpeg'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/2y/6v0z6hpx4dld3z66yqzqglnh0000gn/C/calibre_4.23.0_tmp_iujYOS/6_ST3g.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1089ca0d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x1089ca490>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/2y/6v0z6hpx4dld3z66yqzqglnh0000gn/C/calibre_4.23.0_tmp_iujYOS/OjYbwN.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/2y/6v0z6hpx4dld3z66yqzqglnh0000gn/C/calibre_4.23.0_tmp_iujYOS/gOJdck.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly: Dreams of Light
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/

**Comment by fullerenedream** [comment]
I'm having a similar problem. Calibre 4.23.0, DeDRM 6.8.0 - but I'm on macOS Mojave (10.14.6), not Catalina.

I installed the newest Calibre update yesterday, and today when I try to strip the DRM from an .azw file (downloaded on Kindle for Mac 1.17.1), I get this error:

"Cannot convert Pepper's Special Wings. This book is locked by DRM. To learn more about DRM and why you cannot read or convert this book in calibre, click here."

So I checked the troubleshooting info and rolled Calibre back to 4.23.0, and made sure I have the most recent DeDRM, but I'm still getting the error.

Looking around the Issues page, it seems quite a few people are encountering similar problems.

I hope it turns out to be an easy fix! Thank you!!!



Here's Calibre's debug log:

Traceback (most recent call last):
  File "site-packages/calibre/gui2/ui.py", line 157, in __init__
  File "site-packages/calibre/gui2/ui.py", line 171, in init_iaction
  File "site-packages/calibre/customize/__init__.py", line 613, in load_actual_plugin
  File "lib/python2.7/importlib/__init__.py", line 37, in import_module
  File "site-packages/calibre/customize/zipplugin.py", line 185, in load_module
  File "calibre_plugins.similar_stories.action", line 12, in <module>
ImportError: No module named PyQt4.Qt
libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Quality Check (1, 10, 1) && Similar Stories (1, 0, 58) && Find Duplicates (1, 7, 2) && KindleUnpack - The Plugin (0, 81, 5) && Open With (1, 5, 12)
calibre 4.23  embedded-python: True is64bit: True
Darwin-18.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '18.7.0', 'Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64')
Python 2.7.16
OSX: ('10.14.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 8, 0) && Quality Check (1, 10, 1) && Similar Stories (1, 0, 58) && Find Duplicates (1, 7, 2) && KindleUnpack - The Plugin (0, 81, 5) && Open With (1, 5, 12)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 141.000002118 x 141.000002118
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.37] splash screen shown
[0.38] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[1.67] main UI initialized...
[1.67] Hiding splash screen
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.91:  0.817) _startup_on_demand listening on port 9090
SMART_DEV (   0.95:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.98:  0.000) _startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   2.00:  1.002) run All IP addresses {u'lo0': [{'netmask': u'255.0.0.0', 'peer': u'127.0.0.1', 'addr': u'127.0.0.1'}], u'en0': [{'netmask': u'255.255.255.0', 'broadcast': u'10.150.0.255', 'addr': u'10.150.0.176'}]}
[19.94] splash screen hidden
[19.95] Started up in 19.95 seconds with 1112 books
Worker Launch took: 0.103940963745
Job: 0 Convert book 1 of 1 (Pepper's Special Wings) finished
Convert book 1 of 1 (Pepper's Special Wings)
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'generic_eink'
	  read_metadata_from_opf: u'/var/folders/d1/m9bvj51d0fzg5stlrl1gfbmc0000gn/C/calibre_4.23.0_tmp_IYjfR4/eaeFan.opf'
	  cover: u'/var/folders/d1/m9bvj51d0fzg5stlrl1gfbmc0000gn/C/calibre_4.23.0_tmp_IYjfR4/dJGLh1.jpeg'
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/d1/m9bvj51d0fzg5stlrl1gfbmc0000gn/C/calibre_4.23.0_tmp_IYjfR4/dJGLh1.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1133098d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x113309cd0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/d1/m9bvj51d0fzg5stlrl1gfbmc0000gn/C/calibre_4.23.0_tmp_IYjfR4/eaeFan.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/d1/m9bvj51d0fzg5stlrl1gfbmc0000gn/C/calibre_4.23.0_tmp_IYjfR4/BMpNrn.azw
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly: Pepper's Special Wings
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 187, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 121, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
	  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 47, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: Pepper's Special Wings

**Comment by ElleKayEm** [comment]
DRM removal happens when you first add a book to calibre, not during conversion.  Here's how to get the log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by ptbriody** [comment]
Thank you ElleKayEM! That worked - I would have never guessed DRM removal happens when adding to the library. I deleted all the books that had failed, re-added them, and then converted. Thanks!

**Comment by tartley** [comment]
Proposed README update mentions this fact right at the step 'Remove DRM: Import the book into Calibre'. https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM#3-import-the-book-calibre
