### ISSUE TITLE
[feature request] support for comics and manga downloaded with comixology on android

### ISSUE THREAD

**Issue by techno-arch** [apprenticeharper/DeDRM_tools#1583]
Comixology only has there manga/comics in its best quality on android/ios but the manga/comics are stored in a folder with each image encrypted. Can you find a way to decrypt the images

**Comment by ElleKayEm** [comment]
The one project I'm familiar with which deals with Comixology is this one:  https://github.com/Cortys/comic-backup

**Comment by techno-arch** [comment]
> The one project I'm familiar with which deals with Comixology is this one:  https://github.com/Cortys/comic-backup

Comixology on web browsers uses much lower quality images.

**Comment by Darkwolf1515** [comment]
Would be amazing if comiXology could be supported here, I know that it’s possible to do.

**Comment by ElleKayEm** [comment]
Apprentice Harper is always open to pull requests.

**Comment by AdmiralAsshat** [comment]
>Comixology on web browsers uses much lower quality images.

I was unaware of this, so I went to compare. I have a couple of comics that I bought specifically from Comixology (not realizing that ones you buy *on Comixology* don't show up in the Kindle app, even though the reverse is true), and then had to rip through comic-backup since my normal Amazon->Calibre workflow wouldn't work.

So essentially, I've got Volumes 1-3 of [Comic] from Kindle, and Volumes 4-6 from Comixology.

In comparing the rips, the image quality is:
Amazon AZW: 1249x1920 pixels
Comixology rip from comix-backup: 1073x1650 pixels

So yeah, it's a **bit** worse...but by my calculations no more than 15%, which is not "much lower" in my book.

**Comment by j-howell** [comment]
Even when obtaining comics from Amazon the image quality varies greatly depending on how the files are delivered. This thread on MobileRead has more info: [Some questions regarding Oasis 2 & comics/manga](https://www.mobileread.com/forums/showthread.php?t=295611)

**Comment by techno-arch** [comment]
amazon kindle is still lower quality then comixology on android. with a volume of a manga i have being around 160mb on kindle for pc and on comixology on android the folder for it is over 300mb

**Comment by ChrisFhey** [comment]
> So yeah, it's a **bit** worse...but by my calculations no more than 15%, which is not "much lower" in my book.

That's only because the current rip method uses the web version, which does not give you the full quality you get in the app.
Hence why people want to figure out a way to create a rip from the app instead.
