### ISSUE TITLE
DeDRM does not remove kindle DRM protection

### ISSUE THREAD

**Issue by numira51** [apprenticeharper/DeDRM_tools#2034]
I followed ReadMe file, but the ebooks .KFX remain protect

Calibre: 5.38.0
Kindle: unknown
DeDRM : 7.21
Log: 
[tmpf4aqjbfp copia.txt](https://github.com/apprenticeharper/DeDRM_tools/files/8235888/tmpf4aqjbfp.copia.txt)

**Comment by ElleKayEm** [comment]
As the log says: Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import.

In order to decrypt KFX files, they must come from Kindle version 1.26 or earlier.  It's possible to get most books in the older formats.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by numira51** [comment]
thank you for the suggestions. I solved everything by downloading the book, which I was interested in, on an old e-ink kindle and, therefore, transferring the file to Calibre.

numira51



> Il giorno 11 mar 2022, alle ore 23:08, ElleKayEm ***@***.***> ha scritto:
> 
> https://www.mobileread.com/forums/showthread.php?t=283371 <https://www.mobileread.com/forums/showthread.php?t=283371>
