### ISSUE TITLE
DeDRM stopped working

### ISSUE THREAD

**Issue by nwl** [apprenticeharper/DeDRM_tools#213]
Running Calibre 2.5.0 (Debian) or Calibre 2.78 (OSX), both with 6.5.2m, I have successfully removed DRM from azw3 files registered to my e-Ink kindle in the past (via copying file via USB to my laptop from the Kindle).  Latest purchase appeared as a kfx file so I downloaded the azw3 file via the website instead, again keyed to my e-Ink kindle.

Running conversion generates the following debug:

Job: 2 Convert book 1 of 1 (BOOK NAME) finished
Convert book 1 of 1 (BOOK NAME)
	Resolved conversion options
	calibre version: 2.5.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/tmp/calibre_2.5.0_tmp_OXzg3C/U0R9sq.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f270edb82d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x7f270edb8950>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/tmp/calibre_2.5.0_tmp_OXzg3C/PRF3Go.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /tmp/calibre_2.5.0_tmp_OXzg3C/5xljnM.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 20, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 195, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_override
	    override_input_metadata=True)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1041, in run
	    accelerators, tdir)
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 241, in __call__
	    log, accelerators)
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/mobi_input.py", line 43, in convert
	    opf = os.path.abspath(mr())
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi8.py", line 77, in __call__
	    self.mobi6_reader.check_for_drm()
	  File "/usr/lib/calibre/calibre/ebooks/mobi/reader/mobi6.py", line 147, in check_for_drm
	    raise DRMError(name)
	calibre.ebooks.DRMError: BOOK NAME

**Comment by ElleKayEm** [comment]
We need an import log to see what's happening with DRM removal.

**Comment by dreki** [comment]
I can confirm this is happening. Amazon has a new kind of DRM.

**Comment by dreki** [comment]
Here's a screenshot of the files that make up one of these new-DRM'd books:

![image](https://cloud.githubusercontent.com/assets/563345/23035051/eda66d80-f44b-11e6-8e9b-6142e1b6d195.png)

**Comment by dreki** [comment]
Here's a log of Importing and attempted conversion of one of these new-DRM'd books:

[tmpcLIhqE.txt](https://github.com/apprenticeharper/DeDRM_tools/files/781159/tmpcLIhqE.txt)

**Comment by dreki** [comment]
Found:
```
DeDRM v6.5.3: Trying to decrypt B00AITRKOM_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
```

**Comment by nwl** [comment]
That doesn't look the file I downloaded which was just a plain azw3 file.

I got my debug from running calibre-debug -g

What flags should I use to get the more verbose import log?

On Thu, Feb 16, 2017 at 10:42:36AM -0800, Sean Gilbertson said:

**Comment by dreki** [comment]
@nwl When you're running Calibre, Click the menu item that says 'Preferences' (_not_ the standard OS X Preferences menu; there's a separate top-level one) and click the item for going into debug mode.

Calibre will create a log file, and when you quit Calibre it will automatically open it up in a text editor.

**Comment by nwl** [comment]
Thanks!

calibre Debug log
calibre 2.78  embedded-python: True is64bit: True
Darwin-15.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.3.0', 'Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.11.3', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 94.0000014117 x 94.0000014117
Starting up...
Started up in 1.56 seconds with 57 books
2017-02-16 10:53:02.906 Calibre[11847:6032831] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.120597839355
Job: 1 Convert book 1 of 1 (BOOK NAME) finished
Convert book 1 of 1 (BOOK NAME)
	Resolved conversion options
	calibre version: 2.78.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/_q/74z9mt0j16v0_2yd9ytzws4r0000gp/C/calibre_2.78.0_tmp_MQZoAP/j3_9tt.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x113a5f5d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x113a5fc90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/_q/74z9mt0j16v0_2yd9ytzws4r0000gp/C/calibre_2.78.0_tmp_MQZoAP/rfGM8c.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: BOOK NAME
	InputFormatPlugin: MOBI Input running
	on /var/folders/_q/74z9mt0j16v0_2yd9ytzws4r0000gp/C/calibre_2.78.0_tmp_MQZoAP/JrLDJ6.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1065, in run
	  File "site-packages/calibre/customize/conversion.py", line 245, in __call__
	  File "site-packages/calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "site-packages/calibre/ebooks/mobi/reader/mobi8.py", line 86, in __call__
	  File "site-packages/calibre/ebooks/mobi/reader/mobi6.py", line 152, in check_for_drm
	calibre.ebooks.DRMError: BOOK NAME

**Comment by klinkehoffen** [comment]
I have the same issue, only since 15 February, running DeDRM_tools_6.5.3 and Calibre 2.53[64bit] (actually, I should import the newer version!). My problem arises on importing .azw files from Amazon onto a Windows 7 PC. It worked perfectly on the 14th, then I suspect Amazon made a change.

My log is as follows:
calibre Debug log
calibre 2.53 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.9
Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM
Starting up...
Started up in 26.74 seconds with 4445 books
DeDRM v6.5.3: Trying to decrypt B00CHCOO7E_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Trying to decrypt B00OD6DZ5E_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Sam\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Sam\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1221412773' and UserName '53616d'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.4 seconds
DeDRM v6.5.3: Trying to decrypt B01M049EHU_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 358, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 270, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 488, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 273, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 301, in identity
MobiError: Unknown book type: ÄÞ|Œ"
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Sam\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Sam\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1221412773' and UserName '53616d'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 358, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 270, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 488, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 273, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 301, in identity
MobiError: Unknown book type: ÄÞ|Œ"
DeDRM v6.5.3: Failed to decrypt with error: KFX format detected. This format cannot be decrypted yet.
DeDRM v6.5.3: Looking for new default Kindle Key after 1.4 seconds
searching for kinfoFiles in C:\Users\Sam\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Sam\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1221412773' and UserName '53616d'
DeDRM v6.5.3: Found 1 new key
DeDRM v6.5.3: Ultimately failed to decrypt after 1.4 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 153, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 1.4 seconds
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 358, in get_file_type_metadata
  File "site-packages\calibre\customize\builtins.py", line 270, in get_metadata
  File "site-packages\calibre\ebooks\metadata\mobi.py", line 488, in get_metadata
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 273, in __init__
  File "site-packages\calibre\ebooks\mobi\reader\headers.py", line 301, in identity
MobiError: Unknown book type: ÄÞ|Œ"
Added B00CHCOO7E EBOK to db in: 1.3
Added B01M049EHU EBOK to db in: 1.2
Added B00OD6DZ5E EBOK to db in: 1.3
Added 3 books in 4.7 seconds

**Comment by dreki** [comment]
I'm happy to report that if you roll back your Kindle app to 1.17.1 (make sure to delete your existing Kindle app _along with all support files_. I recommend using AppCleaner on OS X. If you don't do this step the app may just keep replacing itself with 1.19), you can redownload and convert books once again.

This should be treated as a temporary fix.

**Comment by klinkehoffen** [comment]
That sounds great for Apple. I am not using Kindle app though: I read my files on my PC using Calibre.

**Comment by ElleKayEm** [comment]
@nwl 
Your issue is not the new KFX file type.  Please post a log of importing the AZW3 file into calibre.

@klinkehoffen 
See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by nwl** [comment]
@ElleKayEm Yes, it is not a KFX issue. I think My issue may be getting confused with other problems people are having. But I not clear on how to get a log of the import. The log I posted above was based on calibre-debug -g (Debian) and then restarting calibre in debug mode (OSX). How can I get a more verbose log for you?

**Comment by ElleKayEm** [comment]
@nwl 
Under the Preferences menu, click Restart in debug mode.  Once it reopens, add your book to calibre.  Close calibre and the log will open.

**Comment by nwl** [comment]
Ah, apologies. I was doing this but I wasn't adding the book each time, I was just invoking the convert function. Log below. To restate: my eInk kindle serial number is visible when I go to: Preferences/Plugin/DeDRM/eInk Kindle Books

calibre Debug log
calibre 2.78  embedded-python: True is64bit: True
Darwin-15.3.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '15.3.0', 'Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64')
Python 2.7.11
OSX: ('10.11.3', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 94.0000014117 x 94.0000014117
Starting up...
Started up in 1.76 seconds with 56 books
DeDRM v6.5.3: Trying to decrypt BOOK_NAME.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: BOOK_NAME
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 2 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 168, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.1 seconds
Added BOOK_NAME to db in: 0.0
Added 1 books in 0.8 seconds
2017-02-16 15:14:53.791 Calibre[12583:6490731] deliverNotificationWithTitle()
* Notification delivered.
Worker Launch took: 0.143680095673
Job: 1 Convert book 1 of 1 (BOOK_NAME) finished
Convert book 1 of 1 (BOOK_NAME)
	Resolved conversion options
	calibre version: 2.78.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'/var/folders/_q/74z9mt0j16v0_2yd9ytzws4r0000gp/C/calibre_2.78.0_tmp_xE71TB/BpI26k.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11059f5d0>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': u'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x11059fc90>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'personal_doc': u'[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'/var/folders/_q/74z9mt0j16v0_2yd9ytzws4r0000gp/C/calibre_2.78.0_tmp_xE71TB/Yk4qFM.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	Python function terminated unexpectedly: BOOK_NAME
	InputFormatPlugin: MOBI Input running
	on /var/folders/_q/74z9mt0j16v0_2yd9ytzws4r0000gp/C/calibre_2.78.0_tmp_xE71TB/lRJGca.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 154, in main
	    return run_entry_point()
	  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
	    return getattr(pmod, func)()
	  File "site-packages/calibre/utils/ipc/worker.py", line 195, in main
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 26, in gui_convert
	  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1065, in run
	  File "site-packages/calibre/customize/conversion.py

**Comment by ElleKayEm** [comment]
Apparently the serial number in there is not the correct one.  Try to copy and paste it from the website -- remove any spaces.

**Comment by nwl** [comment]
Serial number was the same on the website as it was configured in Calibre....except it was displayed in upper case (where as the physical device shows it in lower case). Re-inputed the serial number all in upper case and all works! Thanks for your help.

**Comment by ElleKayEm** [comment]
@klinkehoffen if you're still having trouble, open a new issue.

**Comment by klinkehoffen** [comment]
@ElleKayEm - you rock! Perfect solution. Thanks so much
