### ISSUE TITLE
dedrm plugin for calibre not working and decrypting kindle file

### ISSUE THREAD

**Issue by mrkhanakia** [apprenticeharper/DeDRM_tools#227]
Hi Here is the log

calibre Debug log
calibre 2.80  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839161
Starting up...
Started up in 7.87 seconds with 0 books
DeDRM v6.5.3: Trying to decrypt Mind is your Business.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: Mind is your Business
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 0 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Administrator\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Administrator\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1688709760' and UserName '41646d696e6973747261746f72'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 6, header length 232
Extra Data Flags: 3
Decrypting Mobipocket 6 ebook: Mind is your Business
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.3 seconds
Added Mind is your Business to db in: 0.7
Added 1 books in 1.3 seconds

**Comment by ElleKayEm** [comment]
If that book is from an E-ink Kindle (not a Fire), then you need to add the serial number to the plugin customization.  Otherwise make sure you have Kindle for PC version 1.17 or earlier and import a copy from there.  See the FAQs:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#a-recent-change-to-kindle-for-pckindle-for-mac

**Comment by BoatrightTBC** [comment]
To provide the tiniest bit more info, this is a known problem due to Amazon changing the way they store and encrypt files on the pc and mac kindle apps.  There is an active discussion of how to get around this, but to date, there has been little success.  The suggestion above is the only current work-around.
