### ISSUE TITLE
De-DRM not working on Kindle for PC. Key missing??

### ISSUE THREAD

**Issue by celinego** [apprenticeharper/DeDRM_tools#273]
Hi, this is my first post so sorry it's so long but I need to include what I've tried so far.  I have read and tried everything I can find for months, but still , when I open these particular books in Calibre (latest version), it still says they still have DRM.  .  I've reopened Calibre in debug mode so I hope this is the right file to include at the bottom. 

Am running Windows 10 on my laptop with Calibre 1.17 which I've reverted to with Windows de-drm plugin v 6.5.3 which has the default key for Kindle for Mac/PC's displayed.  (Well, at least is says it has the default key) but I don't know it's working! 

The problem books seem to ones which are being offered to me FREE by Amazon, one per month as part of me being a Prime Member.  It's called Kindle First.  Each month I've selected and downloaded one and can import it into Calibre but not open it there (say's due to DRM).   They download as AZW books.  I can of course, open and read them on my devices as normal - just not in Calibre.

I've also download other free books, which aren't part of the Kindle First offer.  They download as ,AZW3 books and import and open into Calibre viewer.  

I've now noticed that the Kindle First books are also part of Kindle Unlimited, the subscription where you pay monthly to download & read as many books as you like.  I don't have Kindle Unlimited, however, I'm kind of expecting that, as I'm being offered one book per month from Kindle Unlimited as a Kindle First book (ie FREE), that when I download it, I SHOULD be able to de-drm it via  Calibre.  After all I am paying my Prime subscription and Kindle First is a free benefit within that.  Is this a silly expectation?  

So Amazon seem to format as follows:

Free ebooks (which are not part of Unlimited) as azw3
Paid for books (which ARE part of Unlimited) as azw3 .... both of which I can open in Calibre, but ...

Free ebooks (which ARE part of Unlimited) as azw which I can't open in Calibre.

I can't tell if that's the reason I can't open these books or if it's just that I don't have the right set up within Calibre to open AZW3 format.

I'm pretty sure I was able to do so months ago.  And when I first noticed it, I even imported the DRM from a previous back up but I used to import keys manually then too.  Unfortunately my back up device fried so can't do that again but surely, if I've downloaded and installed the latest 6.5.3 de-drm correctly, the default key should be correct shouldn't it?  Yet, when looking through the log it keep mentioning trying to look for a key?

What am I missing?  Purely that Amazon Unlimited is involved or should I still be able to de-drm those?

Hoping someone can help.  Also, how do I upload the book to here?  Tried to import from My Kindle Content folder but it says not the right format and to try again as different format.

Here's the log file.  Thanks in advance.

calibre Debug log
calibre 2.83 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.387434555 x 106.325581395
Starting up...
Started up in 17.73 seconds with 957 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\x80\xee\xba\x05\x07S\xf7V\xa2\x9aOg\xb5\x12ac\xa1\xb5=\x8d\x9f\xaf\xfa\xed\xe3\x01\x96\x1f\xd3\xa3\xe0p', 'C:\\Users\\C\xc3\xa9line Godfrey\\Documents\\My Kindle Content\\B01M8PI4IG_EBOK.azw']
DeDRM v6.5.3: Trying to decrypt B01M8PI4IG_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Dead Certain: A Novel
Found 6 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 6 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Cline Godfrey\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Cline Godfrey\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3965578829' and UserName '43e96c696e6520476f6466726579'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Dead Certain: A Novel
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.5 seconds
Added Dead Certain: A Novel to db in: 1.5
Added 1 books in 3.6 seconds
Worker Launch took: 0.652000188828

**Comment by ElleKayEm** [comment]
The problem is that your Windows user name has an accented (non-ASCII) character.  For some reason, this causes an issue with retrieving the key.  Set up a new user account without any non-ASCII characters, install Kindle for PC, calibre, and the DeDRM plugin there.  There shouldn't be any problem with Kindle First books since they are yours to keep, not on loan.  Other books with the AZW3 extension must have already been DRM-free.  Don't worry about uploading a book here.

**Comment by celinego** [comment]
Thank you ElleKayEm.  That would the acute accent over the first e in my first name then ... Céline.  That's rather unfortunate.  I assume you mean create a new Windows Account?  Is there no way I can just manually input the key or could someone send it to me to download/save and input?

If I have to set up a new Windows or Microsoft Account and install Kindle for PC on that, how would that affect the registration of my laptop as a device to my existing Amazon account?  Would I have to download books via my existing Amazon login and then move the book to the new user folders (I assume a new set of folders including My Kindle Content will be created under the new user name)?  

Sorry if I'm being obtuse - just wondering how a new user account would work and if it would cause any other problems or conflicts with?

Really appreciate your advice as I'm just unsure if the new account needs to be a completely different name from the current one or, more importantly, do I use the same email address as my current one ... or a different one?

**Comment by ElleKayEm** [comment]
Each Kindle app/device has its own unique key even on the same Amazon account.  The issue with non-ASCII Windows user names is a bug that Apprentice Harper is aware of, but hasn't been able to squash yet.  I can't really say what you should do about your Windows user accounts.  One thing that would be easier than emailing files to yourself is to share a folder between users.

**Comment by celinego** [comment]
Ah, see I hadn't even thought about sharing a folder between the two.  Thanks again. I really do appreciate all the help.  Please tell Apprentice Alf I send him every good wish and lots of luck in his quest to quash the non-ASCII bug.  I, for one, will be extremely grateful.  Also I think the whole team there does a fabulous job so thanks again.  Really appreciate it.

**Comment by apprenticeharper** [comment]
If anyone has any ideas on how to fix this bug, I'd welcome them. I've tried everything I could think of, other than carefully tracing through the Kindle for PC app.

**Comment by shhivam** [comment]
It was I think due to the prime function in src/kindlekey.py which I have corrected now and created the pull request.
I think you should check that out.

**Comment by ElleKayEm** [comment]
I believe the problem with non-ASCII characters in Windows user names was fixed with release 6.5.5.

**Comment by Sophist-UK** [comment]
I do not have any non-ASCII characters in my user name, But the plugin cannot find the default kindle key and consequently cannot decrypt any files.

Can anyone help me to find and import the key?

**Comment by j-howell** [comment]
> Can anyone help me to find and import the key?

What version of Kindle for PC are you using? These tools will not work with version 1.25 or newer.

**Comment by Sophist-UK** [comment]
I just downgraded to 1.24.51068 and was able to find and import the default key (though I did rename it).

But it still will not import files decrypted - Author "Unknown" Title like "B000JMKWTI EBOK".

**Comment by Sophist-UK** [comment]
Ah - it may be a KFX book (even though it is B000JMKWTI_EBOK.azw.

**Comment by Sophist-UK** [comment]
Installed KFX import plugin and now it is working - thanks for your help.

**Comment by philgoetz** [comment]
> I just downgraded to 1.24.51068 and was able to find and import the default key (though I did rename it).

How did you downgrade? Where did you get an install file, & how do you keep it from auto-updating? I have my Kindle for PC set to not automatically install updates, but it does anyway.

**Comment by ElleKayEm** [comment]
> How did you find your Kindle key? I've found no information on how to do this using Google, only blogs saying "it's easy", with no specifics.

When you import a book from Kindle for PC and calibre with DeDRM is on the same machine and user, the key is automatically retrieved.

> How did you downgrade?

Follow the uninstall/reinstall instructions in this section of the FAQs (but you can use 1.24 or earlier):

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

> Where did you get an install file?

See the bottom of the first post here:

https://www.mobileread.com/forums/showthread.php?t=283371

> How do you keep it from auto-updating? I have my Kindle for PC set to not automatically install updates, but it seems to have done so anyway.

Before uninstalling your current version, make sure auto-update is unchecked.  Then when you have the older version installed, make sure to uncheck auto-update again and save settings.

**Comment by davidbbell** [comment]
I have gone through all of the steps, but I continue to get the message "This book is locked by DRM. To learn more …"  I restarted in debug mode and here is the log I received. I appreciate any help you can give me to find what I am doing wrong. I see that it says "No key found in {0:d} PIDs tried." Is this because I copied the kindle book from an old computer (my computer won't run Kindle 1.17)? Do I need to run kindle on the same computer that I am running Calibre?

Thanks

ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-08-05 17:28:07.765 calibre-debug[23682:7782463] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.16  embedded-python: True
macOS-14.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Obok DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
macOS-14.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.01] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.83] GUI main window shown
[0.85] main UI initialized...
[0.85] Hiding splash screen
2024-08-05 17:28:26.715 calibre-debug[23682:7782463] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2024-08-05 17:28:26.715 calibre-debug[23682:7782463] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing /Users/davidbenjaminbellkruse/Downloads/Creciendo_juntas-old_kindle.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.9: Trying to decrypt Creciendo_juntas-old_kindle.azw
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Creciendo juntas: Una guía para profundizar las conversaciones entre mentoras y discipulas (Spanish Edition)
Got DSN key from database 1722871308
Found 4 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 4 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kinf2018 file: /Users/davidbenjaminbellkruse/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'davidbenjaminbellkruse'  on file  /Users/davidbenjaminbellkruse/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'f7b1df28a653'
trying IDString: b'f7b1df28a652'
[11.99] splash screen hidden
[11.99] Started up in 11.99 seconds with 1 books
trying IDString: b'9310232bd125'
trying IDString: b'6530c8009727'
Decrypted key file using IDString '6530c8009727' and UserName 'davidbenjaminbellkruse'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidbenjaminbellkruse/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/davidbenjaminbellkruse/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
2024-08-05 17:28:33.739 calibre-parallel[23704:7782952] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Added Creciendo juntas: Una guía para profundizar las conversaciones entre mentoras y discipulas (Spanish Edition) to db in: 0.0
Added 1 books in 1.5 seconds
Worker Launch took: 0.01 seconds

**Comment by ElleKayEm** [comment]
Each installation of the Kindle app has a unique key even if they are
logged into the same Amazon account.  So, yes, calibre/DeDRM needs to be on
the same computer (and user) as the Kindle app which was used to download
that copy of the book.
