### ISSUE TITLE
missing top level file

### ISSUE THREAD

**Issue by Moana3** [apprenticeharper/DeDRM_tools#275]
I keep trying to load the modified DRM but it says it is missing a top level _init_:py file. what do i do?

**Comment by ElleKayEm** [comment]
There is more than just the plugin in the tools archive.  Unzip it and look in the DeDRM calibre plugin folder for the zip to load into calibre.

**Comment by Moana3** [comment]
the alfcrypto_src zip? it still says that there's an error and is miising the same file

**Comment by Moana3** [comment]
I have the kindle plugin installed, and Ive tried the regular DeDRM plugin but that won't convert the azw4 file that I am trying to do.

**Comment by Moana3** [comment]
I tried.  Perhaps I am doing it wrong?  I don't have the best tech skills.
I have followed the instructions given on the webpage
www.ereader-palace.com/convert-azw4-perfect-pdf/     and
www.ereader-palace.com/calibre-drm-removal-plugins-download-use/

Sorry if I sound anxious but I am moving to a country soon where internet
is super expensive. So I need to find a way to store my Kindle books and
read them without using Kindle.  I honestly prefer a PDF file but haven't
been able to find a way to convert azw4 to anything else.

please help .

**Comment by ElleKayEm** [comment]
Ah, you downloaded the plugin elsewhere.  I wondered what the modified DeDRM plugin was.  I'd never heard of that or the ereader-palace before.

First, since AZW4 files are often textbooks available for rent, you should know that these tools don't work with rented books.  If it's a book you own, then I can help.

I'd suggest removing any old DeDRM plugins or ones from elsewhere.  Download DeDRM_tools_6.5.3.zip from here:

https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.5.3

Unzip that and look inside the DeDRM_calibre_plugin folder.  DeDRM_plugin.zip is the file to load into calibre.

If you downloaded the book with Kindle for PC/Mac, you should be all set.  If it's from or for an E-ink Kindle (not a Fire), you need to enter its serial number into the plugin customization.  Then restart calibre before adding your books.

Once the DRM is removed, the Kindle Unpack plugin is best way to extract the PDF.

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
