### ISSUE TITLE
Unable to remove DRM from Kindle for Windows

### ISSUE THREAD

**Issue by KKSergio** [apprenticeharper/DeDRM_tools#284]
Hello, I have a 64-bit, just downloaded, Calibre version.
I imported the DeDRM tool but it didn't work.
Below please find the logfile. Can you help me please? :-)
Thank you!
PdS

> calibre Log di debug
> calibre 2.85.1 [64bit]  embedded-python: True is64bit: True
> Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
> ('Windows', '7', '6.1.7601')
> Python 2.7.9
> Windows: ('7', '6.1.7601', 'SP1', 'Multiprocessor Free')
> Successfully initialized third party plugins: DeDRM (6, 5, 3)
> devicePixelRatio: 1.0
> logicalDpi: 120.0 x 120.0
> physicalDpi: 72.035450517 x 72.0
> Starting up...
> Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
> Started up in 6.93 seconds with 23 books
> Worker Launch took: 0.611999988556
> Job: 1 Converti libro 1 di 1 (The Culture Map: Breaking Through the Invisible Boundaries of Global Business) finished
> Converti libro 1 di 1 (The Culture Map: Breaking Through the Invisible Boundaries of Global Business)
> 	Conversion options changed from defaults:
> 	  output_profile: 'generic_eink'
> 	  read_metadata_from_opf: u'C:\\Users\\Sergio\\AppData\\Local\\Temp\\calibre_hxygdq\\n3x06h.opf'
> 	  verbose: 2
> 	  cover: u'C:\\Users\\Sergio\\AppData\\Local\\Temp\\calibre_hxygdq\\uqavyw.jpeg'
> 	Resolved conversion options
> 	calibre version: 2.85.1
> 	{'asciiize': False,
> 	 'author_sort': None,
> 	 'authors': None,
> 	 'base_font_size': 0.0,
> 	 'book_producer': None,
> 	 'change_justification': u'original',
> 	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
> 	 'chapter_mark': u'pagebreak',
> 	 'comments': None,
> 	 'cover': u'C:\\Users\\Sergio\\AppData\\Local\\Temp\\calibre_hxygdq\\uqavyw.jpeg',
> 	 'debug_pipeline': None,
> 	 'dehyphenate': True,
> 	 'delete_blank_paragraphs': True,
> 	 'disable_font_rescaling': False,
> 	 'duplicate_links_in_toc': False,
> 	 'embed_all_fonts': False,
> 	 'embed_font_family': None,
> 	 'enable_heuristics': False,
> 	 'expand_css': False,
> 	 'extra_css': None,
> 	 'filter_css': u'',
> 	 'fix_indents': True,
> 	 'font_size_mapping': None,
> 	 'format': u'doc',
> 	 'format_scene_breaks': True,
> 	 'html_unwrap_factor': 0.4,
> 	 'inline_toc': False,
> 	 'input_encoding': None,
> 	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000005524588>,
> 	 'insert_blank_line': False,
> 	 'insert_blank_line_size': 0.5,
> 	 'insert_metadata': False,
> 	 'isbn': None,
> 	 'italicize_common_cases': True,
> 	 'keep_ligatures': False,
> 	 'language': None,
> 	 'level1_toc': None,
> 	 'level2_toc': None,
> 	 'level3_toc': None,
> 	 'line_height': 0.0,
> 	 'linearize_tables': False,
> 	 'margin_bottom': 5.0,
> 	 'margin_left': 5.0,
> 	 'margin_right': 5.0,
> 	 'margin_top': 5.0,
> 	 'markup_chapter_headings': True,
> 	 'max_toc_links': 50,
> 	 'minimum_line_height': 120.0,
> 	 'no_chapters_in_toc': False,
> 	 'no_inline_navbars': False,
> 	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000000005524908>,
> 	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
> 	 'pdb_output_encoding': u'cp1252',
> 	 'prefer_metadata_cover': False,
> 	 'pretty_print': False,
> 	 'pubdate': None,
> 	 'publisher': None,
> 	 'rating': None,
> 	 'read_metadata_from_opf': u'C:\\Users\\Sergio\\AppData\\Local\\Temp\\calibre_hxygdq\\n3x06h.opf',
> 	 'remove_fake_margins': True,
> 	 'remove_first_image': False,
> 	 'remove_paragraph_spacing': False,
> 	 'remove_paragraph_spacing_indent_size': 1.5,
> 	 'renumber_headings': True,
> 	 'replace_scene_breaks': u'',
> 	 'search_replace': '[]',
> 	 'series': None,
> 	 'series_index': None,
> 	 'smarten_punctuation': False,
> 	 'sr1_replace': None,
> 	 'sr1_search': None,
> 	 'sr2_replace': None,
> 	 'sr2_search': None,
> 	 'sr3_replace': None,
> 	 'sr3_search': None,
> 	 'start_reading_at': None,
> 	 'subset_embedded_fonts': False,
> 	 'tags': None,
> 	 'timestamp': None,
> 	 'title': None,
> 	 'title_sort': None,
> 	 'toc_filter': None,
> 	 'toc_threshold': 6,
> 	 'transform_css_rules': '[]',
> 	 'unsmarten_punctuation': False,
> 	 'unwrap_lines': True,
> 	 'use_auto_toc': False,
> 	 'verbose': 2}
> 	InputFormatPlugin: MOBI Input running
> 	on C:\Users\Sergio\AppData\Local\Temp\calibre_hxygdq\5hdipe.azw
> 	Found KF8 MOBI of type 'standalone'
> 	Python function terminated unexpectedly
> 	  The Culture Map: Breaking Through the Invisible Boundaries of Global Business (Error Code: 1)
> 	Traceback (most recent call last):
> 	  File "site.py", line 132, in main
> 	  File "site.py", line 109, in run_entry_point
> 	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
> 	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
> 	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
> 	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
> 	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
> 	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
> 	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
> 	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
> 	calibre.ebooks.DRMError: The Culture Map: Breaking Through the Invisible Boundaries of Global Business

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book, not during conversion.  Take a look at the FAQs for how to get the necessary log:  https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by prchvs** [comment]
I have the same issue ... newest update of Calibre, newest update of DRM tools; removed the book before updating, changed calibre behaviour for adding books (overwriting) but it still isn't allowing me to convert to a different format because of DRM

calibre Debug log
calibre 2.85.1  embedded-python: True is64bit: False
Windows-8-6.2.9200 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 3) && Find Duplicates (1, 6, 2)
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.8418079096 x 91.745819398
Starting up...
Failed to read metadata from font file: c:\windows\fonts\calvin and hobbes normal.ttf tuple index out of range
Started up in 6.86 seconds with 402 books
DeDRM v6.5.3: Trying to decrypt Revitalize- Biblical Keys to Helping Your Church Come Alive Again.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Revitalize: Biblical Keys to Helping Your Church Come Alive Again
Found 8 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v6.5.3: Failed to decrypt with error: No key found in 8 keys tried.
DeDRM v6.5.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Renee\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\Renee\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3975281939' and UserName '52656e6565'
DeDRM v6.5.3: Found 1 new key
MobiDeDrm v0.41.
Copyright © 2008-2012 The Dark Reverser et al.
MOBI header version 8, header length 264
Extra Data Flags: 3
Decrypting Kindle Format 8 ebook: Revitalize: Biblical Keys to Helping Your Church Come Alive Again
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds.
Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 170, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 610, in run
  File "calibre_plugins.dedrm.__init__", line 560, in KindleMobiDecrypt
DeDRMError: DeDRM v6.5.3: Ultimately failed to decrypt after 0.2 seconds
Added Revitalize: Biblical Keys to Helping Your Church Come Alive Again to db in: 1.9
Added 1 books in 3.0 seconds
Worker Launch took: 0.197000026703
Job: 1 Convert book 1 of 1 (Revitalize: Biblical Keys to Helping Your Church Come Alive Again) finished
Convert book 1 of 1 (Revitalize: Biblical Keys to Helping Your Church Come Alive Again)
	Conversion options changed from defaults:
	  output_profile: 'kobo'
	  cover: u'C:\\Users\\Renee\\AppData\\Local\\Temp\\calibre_al1wwl\\64j3tl.jpeg'
	  verbose: 2
	  read_metadata_from_opf: u'C:\\Users\\Renee\\AppData\\Local\\Temp\\calibre_al1wwl\\hpxc_3.opf'
	Resolved conversion options
	calibre version: 2.85.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\Renee\\AppData\\Local\\Temp\\calibre_al1wwl\\64j3tl.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x04583990>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x04583DB0>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\Renee\\AppData\\Local\\Temp\\calibre_al1wwl\\hpxc_3.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on C:\Users\Renee\AppData\Local\Temp\calibre_al1wwl\yxtsdp.azw3
	Found KF8 MOBI of type 'standalone'
	Python function terminated unexpectedly
	  Revitalize: Biblical Keys to Helping Your Church Come Alive Again (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 132, in main
	  File "site.py", line 109, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 33, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
	  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 157, in check_for_drm
	calibre.ebooks.DRMError: Revitalize: Biblical Keys to Helping Your Church Come Alive Again

**Comment by apprenticeharper** [comment]
Assumed solved. Closed.
