### ISSUE TITLE
DRM removed for one Adobe PDF in a series, but not the other two books

### ISSUE THREAD

**Issue by ehamlin** [apprenticeharper/DeDRM_tools#404]
This is weird. Works beautifully for one of the three books in a series, all from the same publisher, but upon opening the other books in Calibre (latest 3.12.0) the rights are not stripped. I.e., clicking on them brings up Acrobat Reader with blank pages where the book content should be, whereas with the first book I saw the content pop up as expected and could save a DRM-free PDF from Reader.

What could be going on? I've tried deleting and re-adding the books from Calibre, as well as restarting Calibre with an empty library and reloading the books one at a time. No joy.

**Comment by ElleKayEm** [comment]
Well, it's strange if they're from the same source and downloaded the same way.  Otherwise, maybe not.  [Post a log](https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that) of the one that worked and one of the ones that didn't.

**Comment by apprenticeharper** [comment]
What happens if you open the calibre copy of the book in Adobe Digital Editions?
