### ISSUE TITLE
PDF Woes

### ISSUE THREAD

**Issue by BrooklynWiz** [apprenticeharper/DeDRM_tools#439]
I have successfully managed to convert one of my books into PDF format, but when I try to drag pages to a new PDF they show up blank in the new PDF. Any ideas why this would happen?

**Comment by ElleKayEm** [comment]
If you're able to convert from some other format to PDF, then clearly it's DRM-free.  For other ebook issues, you could try the MobileRead forums.

**Comment by BrooklynWiz** [comment]
It does seem like it is some weird sort of DRM thing, it is only happening for one of the books. I even extracted the pages using a different program but again, as soon as I try to drag them out of the PDF in any form the pages show up blank. I asked on the forum suggested, but is it possible that Calibre is somehow converting the format but not removing copy protection?

FWIW my intentions aren't sinister, I'm a teacher trying to take out an excerpt for my students to read.

**Comment by ElleKayEm** [comment]
Calibre would be unable to convert it at all if the book had DRM.

On the other hand, an embedded font can have its own protection and DeDRM doesn't deal with that.  You could try converting to MOBI (which doesn't support embedded fonts) first and then to PDF.  That might really mess with other formatting though.

I don't know if that's the problem here.  And there's undoubtedly a better way to remove embedded fonts.  But you could give it a try.  Again the MobileRead folks would probably have a better idea.

**Comment by BrooklynWiz** [comment]
Oh ok that makes sense. Thank you!

________________________________
