### ISSUE TITLE
Undefined entity in book

### ISSUE THREAD

**Issue by MegMM** [apprenticeharper/DeDRM_tools#506]
Hello! First, thank you to everyone who's worked on this feature to make it function. It's SO useful and helpful! The deDRM 6.6 Calibre plugin has been working pretty well so far on my Amazon Kindle books (6 so far) importing the Amazon file (via Kindle reader app 1.17.1), de-DRMing and then converting to MOBI, but it choked on one book with the following error: 
"This page contains the following errors:
error on line 74 at column 108: Entity 'nbsp' not defined
Below is a rendering of the page up to the first error..."
[... blank page ...]

It looks like this book (which I think was partially a Gutenberg project) has some html errors probably? I was able to work around this by converting the imported AZW book to Epub (all within Calibre) and the book works in that format. So it looks like it might be a problem in the MOBI conversion. Don't know if it matters but this is on a Windows 10 64-bit platform. Let me know what other info I can clarify for you if you want to fix it. Thanks! -Meghan

**Comment by ElleKayEm** [comment]
DRM removal happens when you add the book to calibre, not during conversion.  For issues with conversion, I suggest looking at the calibre forums at MobileRead.

**Comment by MegMM** [comment]
Alright, I guess I have the deDRM plugin and the autoconvert for AZW files happening at the same time (adding books), so I wasn't catching the difference. Thanks I'll check MobileRead forums.

**Comment by ElleKayEm** [comment]
Oh, I misunderstood.  Sounds like what you're referring to isn't actually conversion.  Kindle for PC/Mac gives the generic AZW extension to all of its book files regardless of format.  When the files are added to calibre and the DRM is removed (or if the file is already DRM-free), DeDRM will change the extension to match the actual format.

To see if the problem is with DeDRM or something else, try disabling the DeDRM plugin and adding the book again.
