### ISSUE TITLE
DeDRM Calibre Plugin problem decrypting KFX

### ISSUE THREAD

**Issue by Monty** [apprenticeharper/DeDRM_tools#522]
I can use Kindle 1.7.1 to load and decrypt the .azw file, but not the kfx format obtained from the later Kindle versions. The debug log seems to contain all the relevant version numbers, etc. If this is not helpful, let me know.

[Calibre_debug-KZW.txt](https://github.com/apprenticeharper/DeDRM_tools/files/2043003/Calibre_debug-KZW.txt)

**Comment by ElleKayEm** [comment]
My guess is not finding the new version's key because there's something left over from the previous installation.  Try following these instructions for completely uninstalling and reinstalling:

https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md#i-have-installed-the-calibre-plugin-and-the-book-is-not-already-in-calibre-but-the-drm-does-not-get-removed-it-is-a-kindle-book

**Comment by Monty** [comment]
The instructions you sent reference "Reinstall Kindle for PC(Mac) version 1.17"  That works fine for me.

Maybe I wasn't clear. I have two computers, I installed Kindle 1.7.1 on one and I can decrypt this eBook just fine. The other has Kindle 1.23.3. That's the one that I sent the log from. It's just that DeDRM won't decrypt the KFX file that Kindle 1.23.3 downloaded. I thought it might point to some shortcoming of the latest DeDRM.

**Comment by ElleKayEm** [comment]
Okay, I thought you had replaced the older version with the newer version.  You have calibre with DeDRM on the machine with Kindle 1.23.3 too?

**Comment by Monty** [comment]
Yep, that’s the one the log is from, and the only one that doesn’t work. 

-- Monty

**Comment by ElleKayEm** [comment]
And you've never had any other installation of Kindle for PC on this machine?  Because DeDRM is unable to retrieve the key.  See these lines from the log:

>Found k4Mac kinf2011 file: /Users/monty/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2011
Found k4Mac kindle-info file: /Users/monty/Library/Application Support/Amazon/Kindle/storage/.kindle-info
Couldn't decrypt file.
Couldn't decrypt file.

Usually that means there's something left over from a previous installation confusing things.

**Comment by Monty** [comment]
Yes, my laptop which has Kindle 1.23.3 also had Kindle 1.6 and probably others due to auto update.

So if I remove all traces of Kindle, then install Kindle 1.23.3 and register it (which will then download only KFX files), DeDRM should work on those files?

**Comment by ElleKayEm** [comment]
Yes, it should.

**Comment by j-howell** [comment]
Version 1.23.3 is from the Mac App Store. I believe others have had problems making App Store versions of Kindle for Mac work with these tools. I suggest using the downloadable installer from Amazon for version 1.23 instead.

**Comment by Monty** [comment]
I put the Kindle app in the trash, emptied the trash, then `rm -rf` every `com.amazon.Kindle/` and other `Kindle/` directories from `~/Library`

I downloaded Kindle 1.23.3 from the Mac App Store, registered it on Amazon, downloaded a KFX book, dragged the .azw file from:
`~/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content` into Calibre and ran conversion to EPUB.

Success! **Brilliant!**

Thanks for the help!
