### ISSUE TITLE
Is there anybody who can remove drm on Adobe 4.5 Epub/Pdf's?

### ISSUE THREAD

**Issue by akinoc** [apprenticeharper/DeDRM_tools#85]
I just bought a book which can be opened at only Adobe Digital Editions 4.5 version. I had already tried nearly 10 different solution of drm removals. Any of them doesnt work. (calibre plugin doesnt work too). Can anyone handle the drm for adobe 4.5? Its driving me nuts that i cant read the book on my kindle paperwhite that i had already paid 25 dollars...

**Comment by ElleKayEm** [comment]
I've not heard of anything yet.  In the future (or until there's a tool for the new DRM), you should always initially open the .acsm file with ADE 2.0.1.  Then you will have a file which can be DeDRMed.  But if you download the epub with ADE 3.0 or newer, then you risk getting the new hardened DRM which these tools can't handle.  Once your purchase has been attached to your Adobe ID, then new downloads of that book with still have that DRM.

I have stuck with ADE 2.0.1 and haven't had any issue.  Of course, this could also be because the stores I buy from haven't started using the new encryption.  If you don't mind answering, what store was this book from?

**Comment by akinoc** [comment]
Thank you for your quick reply buddy:) 
Unfortunatelly ADE 3.0 and 4.5 doesnt let me open .acsm file that it gives wrong encryption error message. I just bought it from a local online book store. its important to find it from any different source as its about turkish taxation regulations.  (legal.com.tr )

Is there any chance to open it by ADE 2.0.1 with some other way?

**Comment by net-buoy** [comment]
This is intriguing.  All the Overdrive epubs (which are all DRM'd)  are downloaded as acsm (which as I understand it, is not a true file format - see https://ebookreadersoftware.wordpress.com/2010/12/10/acsm-files-what-they-are-and-how-to-work-with-them/) and are converted on the fly by ADE 4.5 to epub (see http://help.overdrive.com/customer/portal/articles/1481938-how-to-set-adobe-digital-editions-to-open-acsm-files-automatically for troubleshooting tips)

**Comment by net-buoy** [comment]
so, once ADE opens the acsm file, you can look in your Digital Editions directory and you will find the downloaded epub file.  If ADE can't open an ACSM file which you have properly licensed, then you need to address your question to the vendor or Adobe.

**Comment by akinoc** [comment]
Thanks for your explanation dude:) But when i try to open the acsm file with lower ade version it gaves this error: http://postimg.org/image/yqajz1znn/

I contacted with vendor already and they told me that i need install ade 4.5 at least to read books. If i download the books by ade 4.5 and reinstall ade 2.0.1, i cant read the books also.

**Comment by net-buoy** [comment]
Now I am terrible confused.  You initially said you could open the book with ADE 4.5: "I just bought a book which can be opened at only Adobe Digital Editions 4.5 version."  So open the book with ADE. 

Once the book is open with ADE look for the opened book in your file system, as the opened book is in epub format. 

If you can't open the book with ADE 4.5, talk to your vendor about what you can open it with...  As I said, ACSM is NOT a file format, it is a delivery manager.  Is the online turkish vendor's site rendered also in English?  What is their URL? What do they advise about reading their online epubs? 

To repeate, you should not have to try and open an ACSM file on your computer. You should configure your browser so that the ACSM file is opened by ADE, and ADE will manage the download and convert to epub on the fly, and if it does not do that, then your beef is with your vendor :-)

**Comment by akinoc** [comment]
Here is the link: https://legal.com.tr/icerik/e-kitap-nasil-okunur 
You can see the explanation that they are directing readers to download latest version of ADE on the 3th paragraph by writing " Adobe tarafından sağlanan bu program ücretsizdir. **Burayı tıklayarak**"  (it means click here - burayı tıklayarak). They are only letting their customers to download acsm to your computer. Then click to acsm file and ADM will be handling that automatically as they explain. 

I can download or reads the books from that website by only ADE 4.5.  If i tried to do the same with ADE 1.7- 2.0.1 or 3.0; it gaves the error: "E_ADEPT_CORE_DECRYPT_LICENCE_KEY".

 I had already removed DRM converted some other book in ADE 2.0.1 that other vendor's site.  But this website books DRM's cant be removed. There is a same issue from another member who is blaming the ade 4.5 also:

https://github.com/apprenticeharper/DeDRM_tools/issues/64

I'm sorry for my broken language that i'm trying to my best. And i thank you very much for your efforts:)

**Comment by ElleKayEm** [comment]
The acsm file is just a few lines telling the Adobe Content Server to send you the actual epub book.  If you open the .acsm file with ADE 4.5 and the vendor uses the hardened DRM, then you won't be able to remove the DRM from the epub with the current tools.  If you've already retrieved the book with a newer version of ADE, then you can't go back and try again with 2.0.1.  As far as I know, there is nothing to be done unless you can somehow convince the vendor to reset your purchase.

Going forward with your next epub purchase, my advice is to use ADE 2.0.1 (authorized with your Adobe ID) and only that version.  That version cannot download a file with the new DRM.  If the store says their books are only compatible with a newer version of ADE, then I guess they are requiring all their books to have the new (currently unremovable) DRM.

**Comment by apprenticeharper** [comment]
Elle has described the situation correctly.

Once a book is downloaded using ADE 3.0 or later and using the new DRM, it is not possible to get a copy using the old DRM. However, if a book is first downloaded using ADE 2.0.1, it can only have the old DRM, and will continue to have the old DRM even when downloaded using ADE 3.0 or later.

Some (very few at the moment) stores will only permit the new DRM, and so will not permit downloads using ADE 2.0.1 or earlier.

I don't know of anyone working on breaking the new DRM although, of course, if someone does I'd be very pleased to include that solution in these tools.

**Comment by NoahCardoza** [comment]
I know this is an old issue and a solution has probably already been found but if anyone else runs into this problem, check out this link https://www.epubsoft.com/how-to-remove-drm-from-adobe.html

It works on both Mac and Windows and seems to have done the trick for me!

Good luck!

**Comment by ElleKayEm** [comment]
No, as far as I'm aware, the newer Adobe DRM still cannot be removed.

**Comment by NoahCardoza** [comment]
Huh, I'm not sure which DRM it cracked... Nevermind then.

All I know is that it worked with Adobe Digital Editions 4.5 books.

**Comment by ElleKayEm** [comment]
Better to use ADE 2.0.1 so you know you have the old DRM which can be removed.  And, of course, DeDRM works fine for that.

**Comment by ElleKayEm** [comment]
No need to pay for what DeDRM does for free.

**Comment by bvrulez** [comment]
As far as I understand DeDRM does remove DRM for free and if it does not work then there is no other program that does - especially not one that get's a lot of advertising and you have to pay for.

**Comment by ElleKayEm** [comment]
Too bad you didn't just use these tools for free.  You'll be still be out-of-luck with that program if you run into a store that is actually using the newer Adobe DRM.

**Comment by NoahCardoza** [comment]
That tool is free or was last I checked/used it.

**Comment by ElleKayEm** [comment]
Good to hear you didn't give those scammers any money.  They do sell a program as well.

**Comment by hattesen** [comment]
As @NoahCardoza remarked, the "Epubor Ultimate" software available from https://www.epubsoft.com/ CAN indeed remove DRM from ADE 4.5. But the free version only converts the first 20% of the content. To convert 100% you have to pay a license of about US$30 - quite steep, if you only need to convert a single DRM protected item.
So @bvrulez assertion, that "if DeDRM can't remove it, nothing can" doesn't hold.

**Comment by ElleKayEm** [comment]
@bvrulez is correct.  Epubor cannot do anything that DeDRM can't do.  Save your money.

**Comment by abhineet99** [comment]
So I generated epub from acsm(from google play) using ADE 4.5. My final target device was kindle paperwhite, so I needed .mobi. I'll just tell here what worked and what didn't:
1) Using this DeDRM Plugin on calibre -> Didn't work. As expected.
2) Downloaded epubor ultimate (free version) -> worked, but converts only 20%, didn't get a license
3) Used this https://www.epubsoft.com/how-to-remove-drm-from-adobe.html , worked, and worked fully because they have 30-Day free trial.

So yes, this thing CAN do more than DeDRM. Still awaiting update on https://github.com/apprenticeharper/DeDRM_tools/issues/670 .

**Comment by ElleKayEm** [comment]
Should have come here for help.  DeDRM definitely works on epub and pdf books from Google Play.  As of yet, they have not started using the hardened Adobe DRM.

**Comment by carderne** [comment]
deleted

**Comment by ElleKayEm** [comment]
Happy to report that DeDRM continues to work well for me.

**Comment by Darkwolf1515** [comment]
Tried removing a google play drmed book a month ago (a free one), worked just fine, now that im trying with a paid one, it just endlessly converts in calilbre.

**Comment by Darkwolf1515** [comment]
Updated it, worked, but its very compressed, anyway to fix that?

**Comment by Darkwolf1515** [comment]
Like here it is in google play 
![image](https://user-images.githubusercontent.com/65789901/91631695-09c8aa00-e9cb-11ea-92db-64fe70b2c40e.png)
and this is adobe 
![image](https://user-images.githubusercontent.com/65789901/91631704-151bd580-e9cb-11ea-8add-efc59dc34c3c.png)

**Comment by ElleKayEm** [comment]
That's not just after DRM removal, is it?  That's after converting formats?  In the page setup when converting, check that the output profile is tablet to avoid images getting resized.

**Comment by Darkwolf1515** [comment]
No, that was a screenshot from digital edtions, after playing with it I realized that digital edtions just compresses the hell out of it regardless, so I got a refund and will get the book elsewhere.

**Comment by xxguisseppe** [comment]
Here, in 2023 the plugging doesn´t work anymore.

**Comment by ElleKayEm** [comment]
Try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by xxguisseppe** [comment]
> Try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

thank you, finally, I could install it.
