### ISSUE TITLE
DeDRM not working with Adobe Adept version 6.5.0,

### ISSUE THREAD

**Issue by jrp13149** [apprenticeharper/DeDRM_tools#927]
I can open the ascm file and download and view the document with the latest version of Adobe Digital Editions (4.5.10) but DeDRM tools fail at DRM removal.

Performing a status check on the supplier server shows it is using Adept DRM v6.5.0

**Comment by ElleKayEm** [comment]
Adobe Content Server 5 and above can deliver the hardened DRM that these tools can't handle.  If you could open and view with ADE 2.0.1 authorized with your Adobe ID, then you'd be okay.  But with ADE 3 and later, you can get the hardened DRM that can't be removed.  As far as I know, it hasn't been figured out yet.  Or at least, no one's shared it with the Apprentices.

**Comment by jrp13149** [comment]
I removed ADE 4, cleaned out all registry keys, rebooted, and installed ADE 2.0.1. I tried to open the ascm file, and got the error message below. I then tried downloading a different, new book and got the same message:

![image](https://user-images.githubusercontent.com/12527314/67935839-9693b300-fbc2-11e9-833e-3b01d2d76232.png)

**Comment by ElleKayEm** [comment]
Seems like they require use of apps that can utilize the hardened DRM.

**Comment by ZolaLa9** [comment]
Thank you **jrp13149** for doing the tests and reporting back.  

When Adobe's "hardened DRM" was first announced, it was reported that there would be 3 settings that vendors could choose from:

1. Regular, non-hardened DRM for all users
2. Regular DRM for users of ADE 1 or 2 and hardened DRM for users of ADE 3+ — and once a book was downloaded into ADE 3+ with hardened DRM, it would no longer be possible to go back and open it in ADE 1 or 2. 
3. Hardened DRM enforced for all users — meaning ADE 3+ required to open books.

I don't know if all 3 choices ended up being implemented as discussed, but given your results, it does appear that number 3 is in play.  

There was also discussion that this "hardened DRM" would have time-sensitive keys, so that users would need to connect to the Internet to get new keys periodically in order to keep reading their books. Again, I don't know if these reports were accurate or not.

**Comment by jrp13149** [comment]
Thanks both, it certainly seems option 3 is out there in the wild. I can see other fields in the ascm file that appear to relate to key validity durations that would allow for time-sensitive keys. I'll close this issue just now, and watch to see if any progress is made on tackling the hardened DRM.

**Comment by ElleKayEm** [comment]
Library books with the older DRM will, of course, expire at the end of the lending period.  But no requirement to connect to the internet periodically like the hardened version is suggested to have.
